#!/bin/sh

#判断是不是远端仓库
IS_BARE=$(git rev-parse --is-bare-repository)
if [ -z "$IS_BARE" ]; then
echo >&2 "fatal: post-receive: IS_NOT_BARE"
exit 1
fi

unset GIT_DIR
DeployPath="/home/www/hello_project/" 

echo "==============================================="
cd $DeployPath  #进入web项目目录
echo "deploying the web project"

#git stash
#git pull origin master #不建议使用git pull，后面会有解释

git fetch --all  #这里使用git fetch进行拉取，不建议用git pull
git reset --hard origin/master

#gitbook build  #这里的gitbook是一个电子文档管理软件，用于生成好固定格式的电子文档，一般用户到，若需要则需另行安装，由于gitbook是node.js写的，而npm是node.js的包管理器，所以要先安装npm再安装gitbook。gitbook build表示文档生成在当前目录的默认文件夹_book里面。
#sleep 15 #gitbook执行需要8秒钟时间，等待15秒是为了确保能得到返回结果

time=`date`
echo "web server pull at webserver at time: $time."
echo "================================================"
